DROP TABLE tb_address_audit

-- TABELA DE AUDITORIA
CREATE TABLE tb_address_audit (
    audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation        VARCHAR2(10), 
    address_id       NUMBER,       
    changed_by       VARCHAR2(255),
    change_timestamp TIMESTAMP    
);

-- TRIGGER
CREATE OR REPLACE TRIGGER trg_tb_address_audit
AFTER INSERT OR UPDATE OR DELETE ON tb_address
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    END IF;

    INSERT INTO tb_address_audit (operation, address_id, changed_by, change_timestamp)
    VALUES (
        v_operation,
        NVL(:NEW.id, :OLD.id), 
        SYS_CONTEXT('USERENV', 'SESSION_USER'), 
        SYSTIMESTAMP 
    );
END;

-- TESTES

INSERT INTO tb_address (street, num, city, state, zip_code)
VALUES ('Rua teste', '123', 'São Paulo', 'SP', '01234-567');

SELECT * from tb_address;

UPDATE tb_address
SET street = 'Rua B'
WHERE id = 6;

DELETE FROM tb_address
WHERE id = 6;

commit;

SELECT * FROM tb_address_audit ORDER BY change_timestamp DESC;
