DROP TABLE tb_clinic_audit

-- TABELA DE AUDITORIA
CREATE TABLE tb_clinic_audit (
    audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation        VARCHAR2(10), 
    address_id       NUMBER,       
    changed_by       VARCHAR2(255),
    change_timestamp TIMESTAMP    
);

-- TRIGGER
CREATE OR REPLACE TRIGGER trg_tb_clinic_audit
AFTER INSERT OR UPDATE OR DELETE ON tb_clinic
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
    ELSIF DELETING THEN
        v_operation := 'DELETE';
    END IF;

    INSERT INTO tb_clinic_audit (operation, address_id, changed_by, change_timestamp)
    VALUES (
        v_operation,
        NVL(:NEW.id, :OLD.id), 
        SYS_CONTEXT('USERENV', 'SESSION_USER'), 
        SYSTIMESTAMP 
    );
END;

--- TESTES ---
select * from tb_clinic;

--CRIAÇÃO
BEGIN
    clinic_pkg.INSERT_CLINIC(
        CNPJ => '12.345.678/0001-90',
        EMAIL => 'contato@clinica.com',
        NAME => 'Clinica Teste',
        PHONE => '(11) 99999-9999',
        ADDRESS_ID => 7
    );
END;

--EXCEPTION
BEGIN
    clinic_pkg.INSERT_CLINIC(
        CNPJ => '12.345.678/0001-90',
        EMAIL => 'clinica.com',
        NAME => 'Clinica Teste',
        PHONE => '(11) 99999-9999',
        ADDRESS_ID => 7
    );
END;

--UPDATE
BEGIN
    clinic_pkg.UPDATE_CLINIC(
        p_id => 14,
        p_cnpj => '12.345.678/0001-90',
        p_email => 'novoemail@clinica.com',
        p_name => 'Clinica Atualizada',
        p_phone => '(11) 88888-8888'
    );
END;

--DELETE
BEGIN
    clinic_pkg.DELETE_CLINIC(p_id => 14);
END;


--VALIDAÇÃO AUDIT
SELECT * FROM tb_clinic_audit ORDER BY change_timestamp DESC;
